# Generated by Django 2.0.3 on 2018-03-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("authentication_service", "0003_auto_20180311_1036")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verified_email",
            field=models.BooleanField(default=False),
        )
    ]
