# Generated by Django 2.0.3 on 2018-03-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("authentication_service", "0004_user_verified_email")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_stop_point",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True,
                error_messages={"unique": "A user with that email already exists."},
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
