# Generated by Django 2.0.3 on 2018-03-30 23:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("authentication_service", "0005_auto_20180317_0205")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="shared_networks",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        )
    ]
