# Generated by Django 2.0.7 on 2018-08-17 07:10

import authentication_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_service', '0007_user_other_details'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authentication_service.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='claimed_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, error_messages={'unique': 'You have an account with us already, Login instead'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
