# Generated by Django 2.0.7 on 2018-09-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_service', '0008_auto_20180817_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
