# Generated by Django 2.0.7 on 2018-10-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_service', '0009_user_email_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feature_notification',
            field=models.BooleanField(default=True),
        ),
    ]
