# Generated by Django 2.0.7 on 2019-02-07 15:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_service', '0012_plan_userplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'You have an account with us already, Login instead'}, max_length=254, unique=True, verbose_name='email address')),
                ('country', models.CharField(max_length=200, null=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('verified_email', models.BooleanField(default=False)),
                ('email_subscribed', models.BooleanField(default=False)),
                ('feature_notification', models.BooleanField(default=True)),
                ('other_details', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('business_id', models.CharField(db_index=True, max_length=6, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('company_size', models.CharField(blank=True, choices=[('self-employed', 'Self employed'), ('2_TO_10', '2-10 employees'), ('11_TO_50', '11-50 employees'), ('51_TO_200', '51-200 employees'), ('200+', '200+ employees')], max_length=100)),
                ('website', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AgentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('last_renewed', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, choices=[('quarterly', 'quarterly'), ('semi_annual', 'semi_annual'), ('annual', 'annual'), ('monthly', 'monthly'), ('annually', 'annually')], max_length=100, null=True)),
                ('plan_info', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='plan',
            name='kind',
            field=models.CharField(choices=[('client', 'client'), ('agent', 'agent')], default='client', max_length=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='duration',
            field=models.CharField(blank=True, choices=[('quarterly', 'quarterly'), ('semi_annual', 'semi_annual'), ('annual', 'annual'), ('monthly', 'monthly'), ('annually', 'annually')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication_service.Plan'),
        ),
        migrations.AddField(
            model_name='agentplan',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication_service.Plan'),
        ),
        migrations.AddField(
            model_name='agentplan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='authentication_service.Agent'),
        ),
    ]
