# Generated by Django 2.0.7 on 2019-02-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_service', '0013_auto_20190207_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
