# Generated by Django 2.0.7 on 2019-02-12 03:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_service', '0014_agent_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
