# Generated by Django 2.0.3 on 2018-03-14 10:42

from django.db import migrations, models
import registration_service.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CVProfile',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('created',
                 registration_service.models.fields.CreationDateTimeField(
                     auto_now_add=True, verbose_name='created')),
                ('modified',
                 registration_service.models.fields.ModificationDateTimeField(
                     auto_now=True, verbose_name='modified')),
                ('mission_statement', models.TextField(blank=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
