# Generated by Django 2.0.3 on 2018-03-14 13:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvprofile',
            name='certifications',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='cvprofile',
            name='educations',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='cvprofile',
            name='industry_skills',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='cvprofile',
            name='softwares',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='cvprofile',
            name='trainings',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='cvprofile',
            name='work_experiences',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
