# Generated by Django 2.0.3 on 2018-03-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_service', '0002_auto_20180314_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
