# Generated by Django 2.0.3 on 2018-03-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_service', '0003_cvprofile_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvprofile',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
