# Generated by Django 2.0.3 on 2018-05-24 21:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_service', '0004_cvprofile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvprofile',
            name='cv_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='cvprofile',
            name='job_category',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='cvprofile',
            name='job_position',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='cvprofile',
            name='thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
