# Generated by Django 2.0.3 on 2018-07-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_service', '0005_auto_20180524_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvprofile',
            name='level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
