# Generated by Django 2.0.3 on 2018-03-06 17:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('section', models.IntegerField(choices=[(1, 'mission-statement')], default=1)),
            ],
            bases=(models.Model, django_app.models.ModelMixin),
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
            ],
            bases=(models.Model, django_app.models.ModelMixin),
        ),
        migrations.CreateModel(
            name='JobCVScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(db_index=True, max_length=100)),
                ('job_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_app.JobCategory')),
            ],
            bases=(models.Model, django_app.models.ModelMixin),
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None)),
                ('software_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None)),
                ('industry_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None)),
                ('job_categories', models.ManyToManyField(to='django_app.JobCategory')),
            ],
            bases=(models.Model, django_app.models.ModelMixin),
        ),
        migrations.AddField(
            model_name='jobcvscript',
            name='job_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_app.JobPosition'),
        ),
        migrations.AddField(
            model_name='jobcvscript',
            name='script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_app.CVScript'),
        ),
    ]
