# Generated by Django 2.0.2 on 2018-03-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_auto_20180307_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvscript',
            name='section',
            field=models.IntegerField(choices=[(1, 'Mission Statement'), (2, 'Work Achievement'), (3, 'Industry Skills')], default=1),
        ),
        migrations.AlterField(
            model_name='jobcvscript',
            name='level',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
