# Generated by Django 2.0.3 on 2018-03-10 00:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_auto_20180309_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='industry_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), null=True, size=None),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), null=True, size=None),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='software_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
