# Generated by Django 2.0.3 on 2018-03-16 20:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_auto_20180310_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAndSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.IntegerField(choices=[(1, 'Schools'), (2, 'Companies')])),
            ],
        ),
        migrations.CreateModel(
            name='OneOfData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
