# Generated by Django 2.0.3 on 2018-03-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_companyandschool_oneofdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneOfData',
        ),
        migrations.AlterField(
            model_name='companyandschool',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Schools'), (2, 'Companies'), (3, 'Courses'), (4, 'Degrees')]),
        ),
    ]
