# Generated by Django 2.0.3 on 2018-03-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0007_auto_20180323_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyandschool',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
