# Generated by Django 2.0.3 on 2018-05-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0009_auto_20180328_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyandschool',
            name='job_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companyandschool',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Schools'), (2, 'Companies'), (3, 'Courses'), (4, 'Degrees'), (5, 'Job Positions'), (6, 'Softwares'), (7, 'Certification')]),
        ),
        migrations.AlterField(
            model_name='missingrecord',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Schools'), (2, 'Companies'), (3, 'Courses'), (4, 'Degrees'), (5, 'Job Positions'), (6, 'Softwares'), (7, 'Certification')]),
        ),
    ]
