# Generated by Django 2.0.3 on 2018-05-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0010_auto_20180512_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyandschool',
            name='name',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='name',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='missingrecord',
            name='name',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
