# Generated by Django 2.0.3 on 2018-03-30 20:44

from django.db import migrations, models
import django.db.models.deletion
import payment_service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='TemplatInfo',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2,
                                              max_digits=10)),
                ('thumbnail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('created',
                 payment_service.models.fields.CreationDateTimeField(
                     auto_now_add=True, verbose_name='created')),
                ('modified',
                 payment_service.models.fields.ModificationDateTimeField(
                     auto_now=True, verbose_name='modified')),
                ('user', models.IntegerField(null=True)),
                ('discount', models.IntegerField(default=0)),
                ('amount',
                 models.DecimalField(
                     decimal_places=2, default=0, max_digits=10)),
                ('order',
                 models.CharField(
                     default=payment_service.models.base.generate_random,
                     max_length=12,
                     primary_key=True,
                     serialize=False)),
                ('payment_method',
                 models.IntegerField(
                     choices=[(1, 'Paystack'), (2, '2Checkout')], default=1)),
                ('template',
                 models.ForeignKey(
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to='payment_service.TemplatInfo')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
