# Generated by Django 2.0.3 on 2018-03-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='made_payment',
            field=models.BooleanField(default=False),
        ),
    ]
