# Generated by Django 2.0.3 on 2018-03-30 23:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0002_userpayment_made_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={'facebook': 20, 'linkedin': 20, 'twitter': 20})),
            ],
        ),
    ]
