# Generated by Django 2.0.3 on 2018-04-03 21:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0003_referraldiscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
