# Generated by Django 2.0.3 on 2018-04-11 17:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0004_paystackevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaystackEvent',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
