# Generated by Django 2.0.3 on 2018-04-17 20:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0005_auto_20180411_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='discount',
        ),
        migrations.AlterField(
            model_name='referraldiscount',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'facebook': 20, 'google': 20, 'linkedin': 20, 'twitter': 20}),
        ),
    ]
