# Generated by Django 2.0.3 on 2018-05-05 02:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0006_auto_20180417_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatinfo',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='referraldiscount',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'facebook': 10, 'linkedin': 10, 'twitter': 10}),
        ),
        migrations.AlterField(
            model_name='templatinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=10),
        ),
    ]
