# Generated by Django 2.0.3 on 2018-05-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0007_auto_20180505_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatinfo',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
