# Generated by Django 2.0.7 on 2018-08-12 03:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0008_auto_20180505_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='referraldiscount',
            name='price_factor',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'Entry Level': 1.5, 'Executive': 3.75, 'Experienced': 3.75, 'Graduate': 2, 'Intern': 1.5}),
        ),
    ]
