# Generated by Django 2.0.7 on 2018-11-30 16:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import payment_service.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0009_referraldiscount_price_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='PlanPayment',
            fields=[
                ('created',
                 payment_service.models.fields.CreationDateTimeField(
                     auto_now_add=True, verbose_name='created')),
                ('modified',
                 payment_service.models.fields.ModificationDateTimeField(
                     auto_now=True, verbose_name='modified')),
                ('user', models.IntegerField(null=True)),
                ('amount',
                 models.DecimalField(
                     decimal_places=2, default=0, max_digits=10)),
                ('order',
                 models.CharField(
                     default=payment_service.models.base.generate_random,
                     max_length=12,
                     primary_key=True,
                     serialize=False)),
                ('payment_method',
                 models.IntegerField(
                     choices=[(1, 'Paystack'), (2, 'Ravepay')], default=1)),
                ('made_payment', models.BooleanField(default=False)),
                ('extra_data',
                 django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('plan', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('duration',
                 models.CharField(
                     blank=True,
                     choices=[('quarterly', 'quarterly'),
                              ('semi_annual', 'semi_annual'), ('annual',
                                                               'annual')],
                     max_length=100,
                     null=True)),
                ('coupon',
                 models.ForeignKey(
                     blank=True,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='payments',
                     to='payment_service.Coupon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='userpayment',
            options={},
        ),
        migrations.AlterField(
            model_name='referraldiscount',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=payment_service.models.base.default_value,
                null=True),
        ),
        migrations.AlterField(
            model_name='referraldiscount',
            name='price_factor',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default={
                    'base_countries': {
                        'EUR': 'NG',
                        'GBP': 'NG',
                        'GHS': 'GH',
                        'KES': 'KE',
                        'NGN': 'NG',
                        'USD': 'NG',
                        'ZAR': 'ZA'
                    },
                    'currencies': {
                        'EUR': '10',
                        'GBP': '10',
                        'GHS': '50',
                        'KES': '800',
                        'NGN': '2000',
                        'USD': '10',
                        'ZAR': '300'
                    },
                    'rates': {
                        'Entry Level': 1.5,
                        'Executive': 3.75,
                        'Experienced': 3.75,
                        'Free': 0,
                        'Graduate': 2,
                        'Intern': 1.5
                    }
                }),
        ),
        migrations.AlterField(
            model_name='templatinfo',
            name='price',
            field=models.DecimalField(
                decimal_places=2, default=2000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='payment_method',
            field=models.IntegerField(
                choices=[(1, 'Paystack'), (2, 'Ravepay')], default=1),
        ),
    ]
